version: v1.3.1

dsn: postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:8080/
  allowed_return_urls:
    - http://127.0.0.1:8080

  methods:
    password:
      enabled: true

  flows:
    settings:
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      use: code
      
    verification:
      enabled: false
      use: code
      
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:8080/auth/login

    login:
      ui_url: http://127.0.0.1:8080/auth/login
      after:
        default_browser_return_url: http://127.0.0.1:8080/

    registration:
      ui_url: http://127.0.0.1:8080/auth/registration
      after:
        default_browser_return_url: http://127.0.0.1:8080/

log:
  level: debug
  format: text

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://user:password@localhost:1025/?disable_starttls=true
    from_address: "no-reply@example.com"