// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lahaehae/crud_project/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, name, email, balance
func (_m *UserRepo) CreateUser(ctx context.Context, name string, email string, balance int64) (*models.User, error) {
	ret := _m.Called(ctx, name, email, balance)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*models.User, error)); ok {
		return rf(ctx, name, email, balance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *models.User); ok {
		r0 = rf(ctx, name, email, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, name, email, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *UserRepo) DeleteUser(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UserRepo) GetUser(ctx context.Context, id int64) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferFunds provides a mock function with given fields: ctx, fromId, toId, balance
func (_m *UserRepo) TransferFunds(ctx context.Context, fromId int64, toId int64, balance int64) (*models.User, error) {
	ret := _m.Called(ctx, fromId, toId, balance)

	if len(ret) == 0 {
		panic("no return value specified for TransferFunds")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) (*models.User, error)); ok {
		return rf(ctx, fromId, toId, balance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) *models.User); ok {
		r0 = rf(ctx, fromId, toId, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64) error); ok {
		r1 = rf(ctx, fromId, toId, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, name, email, balance
func (_m *UserRepo) UpdateUser(ctx context.Context, id int64, name string, email string, balance int64) (*models.User, error) {
	ret := _m.Called(ctx, id, name, email, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, int64) (*models.User, error)); ok {
		return rf(ctx, id, name, email, balance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, int64) *models.User); ok {
		r0 = rf(ctx, id, name, email, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, int64) error); ok {
		r1 = rf(ctx, id, name, email, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
