FROM golang:1.24-alpine AS builder

WORKDIR /build

# Копируем файлы go.mod и go.sum отдельно
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь проект
COPY . .

# Собираем бинарник клиента
RUN go build -o ./client ./cmd/client/main.go

# Минимальный продакшен-образ
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /build/client ./client

CMD ["/app/client"]
