receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

  debug:
    verbosity: detailed

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

processors:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
